[project]
name = "005-extract-transferability-results"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiida-sssp-workflow",
    "h5py>=3.16.0",
]

[tool.uv.sources]
aiida-sssp-workflow = { path = "../../../../aiida-sssp-workflow" }
